### ISSUE TITLE
Can't pickle local object 'get_tts_dataset'?

### ISSUE THREAD

**Issue by MRS-OBAMA** [fatchord/WaveRNN#112]
Hi, i was trying to train using a custom dataset on Windows 10 64-bit with a gtx 1080, after testing quick_start.py (normally) and after some iffy file path issues i managed to run preprocess.py to my dataset correctly, where it recognizes the files and the .csv properly, but once it's done and i run train_tacotron.py i get:

(full paths omitted for clarity)
```
Traceback (most recent call last):
  File "train_tacotron.py", line 163, in <module>
    tts_train_loop(model, optimiser, train_set, lr, training_steps, attn_example)
  File "train_tacotron.py", line 29, in tts_train_loop
    for i, (x, m, ids, _) in enumerate(train_set, 1):
  File "\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File \Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_tts_dataset.<locals>.<lambda>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

I followed the instructions on the page step by step, torch.cuda.is_available() returns true. I'm not sure what i'm doing wrong?

**Comment by 12ben** [comment]
I got the same problem.

**Comment by fatchord** [comment]
@MRS-OBAMA I'll be able to test this on windows in a couple of days. Thanks for your patience.

**Comment by MRS-OBAMA** [comment]
fixed by changing num_workers to 0 in get_tts_datasets in utils.dataset
