### ISSUE TITLE
import the personal dataset

### ISSUE THREAD

**Issue by doctor-xiang** [fatchord/WaveRNN#121]
hello,everyone.When i import the personal dataset.I met the problem. How can i solve this,thank you.

KeyError: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/media/guo/Storage/WaveRNN/utils/dataset.py", line 145, in __getitem__\n    x = text_to_sequence(self.text_dict[id], hp.tts_cleaner_names)\nKeyError: \'000851\'

**Comment by hassanShabbir1960** [comment]
@doctor-xiang Got any solution? I am facing the same error.

**Comment by hassanShabbir1960** [comment]
It is happening because it did'nt find the audio file with this name, try to check your audio data. Make sure it has all the audios corresponding to the audio id in metadata file
