### ISSUE TITLE
hi,what  your pytorch verison?

### ISSUE THREAD

**Issue by sunnnnnnnny** [fatchord/WaveRNN#132]
I meet a problem, i guess it may be  caused by pytorch version.

Traceback (most recent call last):
  File "train_wavernn.py", line 129, in <module>
    voc_train_loop(voc_model, loss_func, optimiser, train_set, test_set, lr, total_steps, device)
  File "train_wavernn.py", line 57, in voc_train_loop
    hp.voc_target, hp.voc_overlap, paths.voc_output)
  File "/home/zyq/harward/WaveRNN-master/gen_wavernn.py", line 34, in gen_testset
    _ = model.generate(m, save_str, batched, target, overlap, hp.mu_law)
  File "/home/zyq/harward/WaveRNN-master/models/fatchord_version.py", line 208, in generate
    sample = sample_from_discretized_mix_logistic(logits.unsqueeze(0).transpose(1, 2))
  File "/home/zyq/harward/WaveRNN-master/utils/distribution.py", line 111, in sample_from_discretized_mix_logistic
    one_hot = F.one_hot(argmax, nr_mix).float()
AttributeError: module 'torch.nn.functional' has no attribute 'one_hot'

**Comment by byuns9334** [comment]
@sunnnnnnnny I got this problem too. My pytorch version is 1.0.0 and torch.cuda.is_available() value is True.

**Comment by byuns9334** [comment]
@sunnnnnnnny I think the author used pytorch version 1.1.0, could you install pytorch again and retry?

**Comment by sunnnnnnnny** [comment]
@byuns9334  ok,thank you .
