### ISSUE TITLE
preprocess error。HParams not configured yet.Call self.configure().

### ISSUE THREAD

**Issue by winterwindwang** [fatchord/WaveRNN#136]
I run the wavernn on windows.I download the LJSpeech dataset and decomposed it. After that, I edit the hparams.py, point thee decomposed path to wav_path attribute. then I run preprocess.py. it raises an error:
`RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
`
and then i modify preprocess.py by add "if __name__ == '__main__':",it raise the error:`multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\Anaconda3\envs\ML_WDH\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "E:\wangdonghua\WaveRNN-master\preprocess.py", line 23, in process_wav
    m, x = convert_file(path)
  File "E:\wangdonghua\WaveRNN-master\preprocess.py", line 30, in convert_file
    y = load_wav(path)
  File "E:\wangdonghua\WaveRNN-master\utils\dsp.py", line 19, in load_wav
    return librosa.load(path, sr=hp.sample_rate)[0]
  File "E:\wangdonghua\WaveRNN-master\utils\__init__.py", line 53, in __getattr__
    raise AttributeError("HParams not configured yet. Call self.configure()")
AttributeError: HParams not configured yet. Call self.configure()
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:/wangdonghua/WaveRNN-master/preprocess.py", line 89, in <module>
    for i, (item_id, length) in enumerate(pool.imap_unordered(process_wav, wav_files), 1):
  File "D:\Anaconda3\envs\ML_WDH\lib\multiprocessing\pool.py", line 735, in next
    raise value
AttributeError: HParams not configured yet. Call self.configure()`

**Comment by bpopp93** [comment]
Any luck figuring this out? Seeing the same problem. Also had this problem with my own data set.

**Comment by fredrikaurdal** [comment]
I'm experiencing the same error.

**Comment by RichelieuGVG1** [comment]
@lexkoro эта колымага все равно не работает. друг дорогой, выручай!
![image](https://user-images.githubusercontent.com/62996833/136098512-7aaf8249-123b-4e15-b2e1-cec041eaf356.png)
