### ISSUE TITLE
Error while running batched 

### ISSUE THREAD

**Issue by Danhyal-Masood** [fatchord/WaveRNN#141]
command used: python quick_start.py --batched
```
Using device: cuda

Initialising WaveRNN Model...

Trainable Parameters: 4.234M

Initialising Tacotron Model...

Trainable Parameters: 11.088M
/home/danhyal/TTS/WaveRNN/WaveRNN/models/tacotron.py:308: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  self.decoder.r = self.decoder.r.new_tensor(value, requires_grad=False)
+---------+---------------+-----------------+----------------+-----------------+
| WaveRNN | Tacotron(r=2) | Generation Mode | Target Samples | Overlap Samples |
+---------+---------------+-----------------+----------------+-----------------+
|  797k   |     180k      |     Batched     |      None      |      None       |
+---------+---------------+-----------------+----------------+-----------------+
 

| Generating 1/6
Traceback (most recent call last):
  File "quick_start.py", line 126, in <module>
    voc_model.generate(m, save_path, batched, target, overlap, hp.mu_law)
  File "/home/danhyal/TTS/WaveRNN/WaveRNN/models/fatchord_version.py", line 189, in generate
    mels = self.fold_with_overlap(mels, target, overlap)
  File "/home/danhyal/TTS/WaveRNN/WaveRNN/models/fatchord_version.py", line 322, in fold_with_overlap
    num_folds = (total_len - overlap) // (target + overlap)
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

**Comment by AlyoshaVasilieva** [comment]
You must also provide `--target` and `--overlap` arguments to use batched mode. (I don't know good values for these, that's just how I got it working)
