### ISSUE TITLE
The version of librosa

### ISSUE THREAD

**Issue by sih4sing5hong5** [fatchord/WaveRNN#155]
I installed with `pip install -r requirements.txt` and ran `gen_tacotron.py` got
```
Traceback (most recent call last):
  File "gen_tacotron.py", line 165, in <module>
    wav = reconstruct_waveform(m, n_iter=args.iters)
  File "/WaveRNN/utils/dsp.py", line 110, in reconstruct_waveform
    S = librosa.feature.inverse.mel_to_stft(
AttributeError: module 'librosa.feature' has no attribute 'inverse'
```

The librosa version of requirements.txt is `0.6.3`.
I found some [comments](https://stackoverflow.com/a/58671908/3640653) about this
```
The module librosa.feature.inverse was introduced in version 0.7
```

Is there any side effect if upgdating the version of librosa?

**Comment by fatchord** [comment]
Thanks for the heads up. I'll have a look at this when I get the time. Cheers!
