### ISSUE TITLE
Preprocess error - 

### ISSUE THREAD

**Issue by aguazul** [fatchord/WaveRNN#168]
I've ran preprocess.py before on this dataset and it ran just fine.  But now for some reason I'm getting this error Unicode Decode Error.

Any hints?

Thank you!
B

`(pyGPUenv) C:\Users\Brandon\Documents\WaveRNN-master\WaveRNN-master>python preprocess.py

15161 wav files found in "C:/Users/B/Documents/WaveRNN-master/WaveRNN-master/Dataset2/"

Traceback (most recent call last):
  File "preprocess.py", line 74, in <module>
    text_dict = ljspeech(path)
  File "C:\Users\B\Documents\WaveRNN-master\WaveRNN-master\utils\text\recipes.py", line 14, in ljspeech
    for line in f :
  File "C:\Users\B\Anaconda3\envs\pyGPUenv\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 2713: invalid start byte`

**Comment by aguazul** [comment]
I was able to fix this issue.  Rather than delete the issue I will leave it posted in case anyone else has the same issue.  

I resaved my csv file this time being sure to select the UTF-8 encoding.  I am using OpenOffice Open Calc and when I select Save As .csv it gives me the option to select the encoding, so I selected UTF-8 this time and it worked.
