### ISSUE TITLE
Error running preprocess.py

### ISSUE THREAD

**Issue by mrichman** [fatchord/WaveRNN#178]
I got the following error when performing the preprocess step on the LJ speec dataset (crashed halfway through):

```
$ python3 preprocess.py
/home/ubuntu/.local/lib/python3.6/site-packages/numba/errors.py:137: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)

13100 wav files found in "/home/ubuntu/WaveRNN/wav_files/"

+-------------+-----------+--------+------------+-----------+
| Sample Rate | Bit Depth | Mu Law | Hop Length | CPU Usage |
+-------------+-----------+--------+------------+-----------+
|    22050    |     9     |  True  |    275     |    3/4    |
+-------------+-----------+--------+------------+-----------+

█████████░░░░░░░ 6798/13100 multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "preprocess.py", line 53, in process_wav
    np.save(paths.mel/f'{wav_id}.npy', m, allow_pickle=False)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 529, in save
    pickle_kwargs=pickle_kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/numpy/lib/format.py", line 640, in write_array
    array.tofile(fp)
OSError: 39440 requested and 22496 written
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 90, in <module>
    for i, (item_id, length) in enumerate(pool.imap_unordered(process_wav, wav_files), 1):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
OSError: 39440 requested and 22496 written
```

**Comment by mrichman** [comment]
Disregard. Partition was full.
