### ISSUE TITLE
windows系统可以运行这个项目吗？

### ISSUE THREAD

**Issue by xiaomingzhong** [fatchord/WaveRNN#179]
我尝试在windows 10里运行这个项目。
运行train_wavernn.py时报错：
`Traceback (most recent call last):
 File "E:/WaveRNN/train_wavernn.py", line 159, in <module>
    main()  
 File "E:/WaveRNN/train_wavernn.py", line 85, in main
    voc_train_loop(paths, voc_model, loss_func, optimizer, train_set, test_set, lr, total_steps)  
 File "E:/WaveRNN/train_wavernn.py", line 105, in voc_train_loop
    for i, (x, y, m) in enumerate(train_set, 1):  
 File "C:\ProgramData\Anaconda3\envs\WaveRNN\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)  
 File "C:\ProgramData\Anaconda3\envs\WaveRNN\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()  
 File "C:\ProgramData\Anaconda3\envs\WaveRNN\lib\site-packages\torch\_utils.py", line 385, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):  
 File "C:\ProgramData\Anaconda3\envs\WaveRNN\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)  
 File "C:\ProgramData\Anaconda3\envs\WaveRNN\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)  
 File "E:\WaveRNN\utils\dataset.py", line 68, in collate_vocoder
    mel_win = hp.voc_seq_len // hp.hop_length + 2 * hp.voc_pad  
 File "E:\WaveRNN\utils\__init__.py", line 53, in __getattr__
    raise AttributeError("HParams not configured yet. Call self.configure()")
AttributeError: HParams not configured yet. Call self.configure()`

运行train_tacotron.py时报错：
`
Traceback (most recent call last):
 File "E:/WaveRNN/train_tacotron.py", line 202, in <module>
    main()  
 File "E:/WaveRNN/train_tacotron.py", line 98, in main
    tts_train_loop(paths, model, optimizer, train_set, lr, training_steps, attn_example)  
 File "E:/WaveRNN/train_tacotron.py", line 126, in tts_train_loop
    for i, (x, m, ids, _) in enumerate(train_set, 1):  
 File "C:\ProgramData\Anaconda3\envs\WaveRNN\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)  
 File "C:\ProgramData\Anaconda3\envs\WaveRNN\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()  
 File "C:\ProgramData\Anaconda3\envs\WaveRNN\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)  
 File "C:\ProgramData\Anaconda3\envs\WaveRNN\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)  
 File "C:\ProgramData\Anaconda3\envs\WaveRNN\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)  
 File "C:\ProgramData\Anaconda3\envs\WaveRNN\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)  
 File "C:\ProgramData\Anaconda3\envs\WaveRNN\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)  
AttributeError: Can't pickle local object 'get_tts_datasets.<locals>.<lambda>'`

**Comment by xiaomingzhong** [comment]
emm

**Comment by xiaomingzhong** [comment]
emm

**Comment by SUPER-ALEX** [comment]
你好，你的这个错误解决了吗？我遇到的错误和你一样。

**Comment by SUPER-ALEX** [comment]
@xiaomingzhong 
你好，你的这个错误解决了吗？我遇到的错误和你一样。

**Comment by Johnzxf** [comment]
have you fixed this problem? I meet the same issues.

**Comment by CatCraftYT** [comment]
If anyone else is having this issue: I fixed it by removing `hparams.configure()` from `train_wavernn.py` and added `hparams.configure('hparams.py')` to `dataset.py`
