### ISSUE TITLE
Can I get any pointers on getting through a "RuntimeError: error in LoadLibraryA"?

### ISSUE THREAD

**Issue by rotvr** [fatchord/WaveRNN#180]
Python 3.8, CUDA 10.2, Pytorch and all other requirements were installed today
```
python.exe .\quick_start.py
Using device: cuda

Initialising WaveRNN Model...

Trainable Parameters: 4.234M

Initialising Tacotron Model...

Trainable Parameters: 11.088M
C:\dev\wavernn\models\tacotron.py:308: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  self.decoder.r = self.decoder.r.new_tensor(value, requires_grad=False)
+---------+---------------+-----------------+----------------+-----------------+
| WaveRNN | Tacotron(r=2) | Generation Mode | Target Samples | Overlap Samples |
+---------+---------------+-----------------+----------------+-----------------+
|  797k   |     180k      |    Unbatched    |      N/A       |       N/A       |
+---------+---------------+-----------------+----------------+-----------------+


| Generating 1/6
Traceback (most recent call last):
  File ".\quick_start.py", line 108, in <module>
    _, m, attention = tts_model.generate(x)
  File "C:\dev\wavernn\models\tacotron.py", line 406, in generate
    self.decoder(encoder_seq, encoder_seq_proj, prenet_in,
  File "C:\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\dev\wavernn\models\tacotron.py", line 243, in forward
    attn_rnn_in = torch.cat([context_vec, prenet_out], dim=-1)
RuntimeError: error in LoadLibraryA 
```
Thank you.

**Comment by SanjaESC** [comment]
https://discuss.pytorch.org/t/torch-cat-runtimeerror-error-in-loadlibrarya/71188/2

Try downgrading to python 3.7

**Comment by rotvr** [comment]
I can try that, but I think that problem is already fixed:
https://github.com/pytorch/pytorch/pull/35368

**Comment by rotvr** [comment]
No longer getting the runtime error with python 3.7 and pytorch 1.5.
