### ISSUE TITLE
python preprocess.py: AssertionError

### ISSUE THREAD

**Issue by fredrikaurdal** [fatchord/WaveRNN#193]
I'm getting this error log after running python preprocess.py:

```
13100 wav files found in "../Training data/LJSpeech-1.1/wavs/"

Traceback (most recent call last):
  File "preprocess.py", line 72, in <module>
    text_dict = ljspeech(path)
  File "D:[directory]\WaveRNN-master\utils\text\recipes.py", line 9, in ljspeech
    assert len(csv_file) == 1
AssertionError
(pytorch) PS D:[directory]\WaveRNN-master> 
```

I downloaded the LJ Speech Dataset, and kept the default folder structure.

Am I supposed to specify the sentence training data CSV somewhere? If I try and move it to the same folder as my wav files it results in a runtime error.

**Comment by 1zxLi** [comment]
Path rule   ：   wav_path = '.../data/LJSpeech-1.1/'      （Under hparams） 
Delete your wavs/

**Comment by Covac** [comment]
Try removing "/wavs/" from your path, pointing to the directory with .csv file should be sufficient.
