### ISSUE TITLE
train tacotron error

### ISSUE THREAD

**Issue by galoncyryll** [fatchord/WaveRNN#207]
Got everything setup as told in the readme guide. Got this error when running python train_tacotron.py. Has anybody encountered with this error?

```
Traceback (most recent call last):
  File "train_tacotron.py", line 202, in <module>
    main()
  File "train_tacotron.py", line 98, in main
    tts_train_loop(paths, model, optimizer, train_set, lr, training_steps, attn_example)
  File "train_tacotron.py", line 126, in tts_train_loop
    for i, (x, m, ids, _) in enumerate(train_set, 1):
  File "F:\conda\envs\env_pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "F:\conda\envs\env_pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "F:\conda\envs\env_pytorch\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "F:\conda\envs\env_pytorch\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\conda\envs\env_pytorch\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "F:\conda\envs\env_pytorch\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\conda\envs\env_pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_tts_datasets.<locals>.<lambda>'
```

**Comment by FaWeeeZ** [comment]
Same issue for me

**Comment by serg06** [comment]
Same issue for me

**Comment by serg06** [comment]
I was able to fix this by downgrading PyTorch to 1.1.0:

- Found the .whl that matches my system here: https://download.pytorch.org/whl/cu100/torch_stable.html
- Installed it with `pip install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp37-cp37m-win_amd64.whl`
- Downgraded torchvision to match PyTorch 1.1.0's installation instructions: `pip install torchvision===0.3.0`
- Was too lazy to downgrate (the now-incompatible) torchaudio, so just uninstalled it `pip uninstall torchaudio`

**Comment by serg06** [comment]
It looks like the issue is due to the fact that [Python lambdas can't be pickled on Windows](https://discuss.pytorch.org/t/cant-pickle-local-object-dataloader-init-locals-lambda/31857). I am currently trying to find a workaround, but if I cannot, then I guess we have to do it on linux.

**Comment by serg06** [comment]
I was able to fix this by changing this:

In `dataset.py` change `DataLoader( ... num_workers=1 )` to `DataLoader( ... num_workers=0 )`

**Comment by FaWeeeZ** [comment]
@serg06 thank you so much, fixed it for me

**Comment by fatchord** [comment]
thanks @serg06  for helping out here :slightly_smiling_face:

**Comment by serg06** [comment]
Glad to help 😄
