### ISSUE TITLE
Tried to preprocess a custom dataset but it gave me error

### ISSUE THREAD

**Issue by WellImDumb** [fatchord/WaveRNN#218]
Traceback (most recent call last):
  File "preprocess.py", line 72, in <module>
    text_dict = ljspeech(path)
  File "C:\Users\misho\WaveRNN-master\utils\text\recipes.py", line 9, in ljspeech
    assert len(csv_file) == 1
AssertionError

**Comment by serg06** [comment]
The problem is that you have multiple `.csv` files in your `wav_path` (`hparams.py`) so it doesn't know which one to use.

Fix: Delete all wav files except one.
