### ISSUE TITLE
Error During Computing Consensus Step

### ISSUE THREAD

**Issue by rybioinf** [fatchord/WaveRNN#235]
Dear Flye Developers,

I am running into an issue during the computing concencus step. I am working with a prokaryote genome ~5m bp with relatively poor data (ONT run with quality score cutoff of 9, ~12x coverage, plenty of reads 2-5kb). This runs as follows.

[2021-12-09 13:43:32] INFO: >>>STAGE: consensus
[2021-12-09 13:43:32] INFO: Running Minimap2
[2021-12-09 13:43:42] INFO: Computing consensus
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/ryan/miniconda3/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/ryan/miniconda3/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/ryan/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ryan/documents/Flye_Assembly/Flye/bin/flye", line 25, in <module>
    sys.exit(main())
  File "/Users/ryan/documents/Flye_Assembly/Flye/flye/main.py", line 830, in main
    _run(args)
  File "/Users/ryan/documents/Flye_Assembly/Flye/flye/main.py", line 583, in _run
    jobs[i].run()
  File "/Users/ryan/documents/Flye_Assembly/Flye/flye/main.py", line 322, in run
    consensus_fasta = cons.get_consensus(out_alignment, self.in_contigs,
  File "/Users/ryan/documents/Flye_Assembly/Flye/flye/polishing/consensus.py", line 71, in get_consensus
    aln_reader = SynchronizedSamReader(alignment_path, contigs_fasta,
  File "/Users/ryan/documents/Flye_Assembly/Flye/flye/utils/sam_parser.py", line 199, in __init__
    self.shared_manager = multiprocessing.Manager()
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/managers.py", line 553, in start
    self._process.start()
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/Users/ryan/documents/Flye_Assembly/Flye/bin/flye", line 25, in <module>
    sys.exit(main())
  File "/Users/ryan/documents/Flye_Assembly/Flye/flye/main.py", line 830, in main
    _run(args)
  File "/Users/ryan/documents/Flye_Assembly/Flye/flye/main.py", line 583, in _run
    jobs[i].run()
  File "/Users/ryan/documents/Flye_Assembly/Flye/flye/main.py", line 322, in run
    consensus_fasta = cons.get_consensus(out_alignment, self.in_contigs,
  File "/Users/ryan/documents/Flye_Assembly/Flye/flye/polishing/consensus.py", line 71, in get_consensus
    aln_reader = SynchronizedSamReader(alignment_path, contigs_fasta,
  File "/Users/ryan/documents/Flye_Assembly/Flye/flye/utils/sam_parser.py", line 199, in __init__
    self.shared_manager = multiprocessing.Manager()
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/managers.py", line 557, in start
    self._address = reader.recv()
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/Users/ryan/miniconda3/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError

[flye.log](https://github.com/fatchord/WaveRNN/files/7688843/flye.log)

Any advice would be much appreciated.

**Comment by rybioinf** [comment]
I have also tried running Flye with data from a much better run from the same organism (~420x coverage) with the --asm-coverage 100 extension. I still ran into the same error at the same part of the job.
