### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by vitaly-zdanevich** [fatchord/WaveRNN#55]
Tried on fresh CentOS 7 on Google Cloud:

```$ python3 quick_start.py 
Traceback (most recent call last):
  File "quick_start.py", line 2, in <module>
    from models.fatchord_wavernn import Model
  File "/home/vitaly_zdanevich/WaveRNN/models/fatchord_wavernn.py", line 4, in <module>
    from utils.display import *
  File "/home/vitaly_zdanevich/WaveRNN/utils/display.py", line 1, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by vitaly-zdanevich** [comment]
Fixed with
`pip3 install matplotlib  --user`
