### ISSUE TITLE
Preprocess error, audioread.NoBackendError

### ISSUE THREAD

**Issue by buscon** [fatchord/WaveRNN#56]
When I launch preprocess I run into this error:

78678 wav files found in "/home/ubuntu/cats/"

+-------------+-----------+--------+------------+-----------+
| Sample Rate | Bit Depth | Mu Law | Hop Length | CPU Count |
+-------------+-----------+--------+------------+-----------+
|    22050    |     9     |  True  |    275     |     4     |
+-------------+-----------+--------+------------+-----------+
 
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "preprocess.py", line 34, in process_wav
    m, x = convert_file(path)
  File "preprocess.py", line 23, in convert_file
    y = load_wav(path)
  File "/home/ubuntu/WaveRNN/utils/dsp.py", line 17, in load_wav
    return librosa.load(path, sr=hp.sample_rate)[0]
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/librosa/core/audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 68, in <module>
    for i, (id, length) in enumerate(pool.imap_unordered(process_wav, wav_files), 1):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
audioread.NoBackendError

**Comment by buscon** [comment]
This can be closed.
I was getting this error because my samples where in 24bits instead of 16bits.
