### ISSUE TITLE
Training - ValueError: Range cannot be empty (low >= high) unless no samples are taken

### ISSUE THREAD

**Issue by buscon** [fatchord/WaveRNN#59]
Hi,

when I launch the training I get the following error:

$ python train_wavernn.py 
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/matplotlib/font_manager.py:278: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '

Initialising Model...

Trainable Parameters: 4.481M

New WaveRNN Training Session...

+------------+------------+--------+--------------+-----------+
| Remaining  | Batch Size |   LR   | Sequence Len | GTA Train |
+------------+------------+--------+--------------+-----------+
| 500k Steps |     32     | 0.0001 |     1375     |   False   |
+------------+------------+--------+--------------+-----------+
 
Traceback (most recent call last):
  File "train_wavernn.py", line 109, in <module>
    voc_train_loop(voc_model, optimiser, train_set, test_set, lr, total_steps)
  File "train_wavernn.py", line 26, in voc_train_loop
    for i, (x, y, m) in enumerate(train_set, 1):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/waveRNN/utils/dataset.py", line 68, in collate_vocoder
    mel_offsets = [np.random.randint(0, offset) for offset in max_offsets]
  File "/home/ubuntu/waveRNN/utils/dataset.py", line 68, in <listcomp>
    mel_offsets = [np.random.randint(0, offset) for offset in max_offsets]
  File "mtrand.pyx", line 992, in mtrand.RandomState.randint
ValueError: Range cannot be empty (low >= high) unless no samples are taken

**Comment by fatchord** [comment]
@buscon I've just updated wavernn - try it again.

**Comment by theAayushbajaj** [comment]
getting the same error on my dataset
I have removed audios less than 1.5 seconds and less than 5 words of transcription,
still getting the same error

Params:
GTA : True
