### ISSUE TITLE
get_vocoder_datasets() isn't removing mels that exceed tts_max_mel_len

### ISSUE THREAD

**Issue by acrosson** [fatchord/WaveRNN#72]
The `get_vocoder_datasets()` function in `utils/dataset.py` isn't filtering out the data where the mel length exceeds `hp.tts_max_mel_len`

Suggesting update line 38 from:
```
dataset_ids = [x[0] for x in dataset]
```
To:
```
dataset_ids = [x[0] for x in dataset if x[1] <= hp.tts_max_mel_len]
```

Without this it will crash when it tries pulling in the mol GTAs that were never generated because their MEL length exceeded threshold.

NOTE: I trained tacotron using custom dataset.

**Comment by fatchord** [comment]
@acrosson I'm not sure I understand. The tts_max_mel_len is for saving GPU mem when training Tacotron - its not relevant when training WaveRNN (max length is irrelevant in that case since wavernn is trained on sub-sequences of the training examples)

**Comment by acrosson** [comment]
The `dataset.pkl` created during preprocessing has all the files from your data folder. When you train tacotron, pulling in the data using `get_tts_dataset()`, it ignores all longer length files 

```
if len <= hp.tts_max_mel_len :
```
However, after you've trained tacotron, and you want to train WaveRNN, you'll use the `get_vocoder_datasets()` function, which **doesn't ignore** all the longer length MELs. And since the ground truths are generated only from the dataset using function `get_tts_dataset()`
```
train_set, attn_example = get_tts_dataset(paths.data, 8, model.get_r())
create_gta_features(model, train_set, paths.gta)
```

WaveRNN will fail when trying to load ground truths that don't exist

```
Initialising Model...

Trainable Parameters: 4.234M

Loading Weights: "checkpoints/aubri_mol.wavernn/latest_weights.pyt"

+-----------+------------+--------+--------------+-----------+
| Remaining | Batch Size |   LR   | Sequence Len | GTA Train |
+-----------+------------+--------+--------------+-----------+
| 99k Steps |     32     | 0.0001 |     1375     |   True    |
+-----------+------------+--------+--------------+-----------+

| Epoch: 1/861 (3/116) | Loss: 6.0664 | 3.1 steps/s | Step: 900k | Traceback (most recent call last):
  File "train_wavernn.py", line 121, in <module>
    voc_train_loop(voc_model, loss_func, optimiser, train_set, test_set, lr, total_steps)
  File "train_wavernn.py", line 27, in voc_train_loop
    for i, (x, y, m) in enumerate(train_set, 1):
  File "/home/cross/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/cross/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/home/cross/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/cross/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/cross/WaveRNN/utils/dataset.py", line 25, in __getitem__
    m = np.load(f'{self.mel_path}{id}.npy')
  File "/home/cross/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data//dataset_mol/gta/AI000-00003501.npy'
```

**Comment by fatchord** [comment]
@acrosson Ah I see, you're right. Ok so I will push a fix for this in a day or so - however a quick way around this for now is to edit hparams.py and set `hp.tts_max_mel_len = 200000` and then run `train_tacotron.py --force_gta`. Hopefully you can then train wavernn on gta sucessfully.
